Z_IDAKU = ZONE:New("IDAKU")
Z_ELVIS = ZONE:New("ELVIS")
Z_GOOSE = ZONE:New("GOOSE")
Z_SA10 = ZONE:New("sa10")
Z_PALSA10 = ZONE:New("palmyrasa10")
Z_H3PAT = ZONE:New("h3north_patriot")
Z_LCD03 = ZONE_POLYGON:New("Z_LCD03",GROUP:FindByName("Z_LCD03"))
Z_FEZWEST = ZONE_POLYGON:New("FEZ WEST",GROUP:FindByName("ZONE_WEST_FEZ"))
Z_FEZSOUTH = ZONE_POLYGON:New("FEZ SOUTH",GROUP:FindByName("ZONE_SOUTH_FEZ"))
Z_CARRIERCAP = ZONE_POLYGON:New("RENO CAP",GROUP:FindByName("ZONE_CARRIERCAP"))
Z_SYRIANAS = ZONE_POLYGON:New("SYRIAN AIRSPACE",GROUP:FindByName("Z_SYRIANAIRSPACE"))
Z_NOTSYRIAAS = ZONE_POLYGON:New("nonsyria",GROUP:FindByName("nonsyria"))
Z_SYR_FEZ_SOUTH = ZONE_POLYGON:New("Syrian FEZ SOUTH",GROUP:FindByName("Z_SYR_FEZ_SOUTH"))
Z_SYR_FEZ_NORTH= ZONE_POLYGON:New("Syrian FEZ NORTH",GROUP:FindByName("Z_SYR_FEZ_NORTH"))
Z_PATROLZONE1 = ZONE:New("PatrolZone1")
Z_YELTSIN = ZONE:New("YELTSIN")
Z_BORRIS = ZONE:New("BORRIS")
atzone = ZONE:New("attanf")
atco = atzone:GetCoordinate()




